### ISSUE TITLE
reinventing the wheel ?

### ISSUE THREAD

**Issue by gedw99** [moznion/gowrtr#1]
https://github.com/dave/jennifer

**Comment by moznion** [comment]
Thank you for notifying me.

Yes, this library and the pointed library aim the similar (or the same) goal. However, there are some differences. For example, the programming interface is different; gowrtr is not strict (perhaps it seems sloppy).

And a big difference is gowrtr aims immutable programming model. [Immutability](https://github.com/moznion/gowrtr#immutability) section of README.md describes that.

Again, both of the libraries look the similar/same goal. That is no doubt.
