### ISSUE TITLE
Do you have any plans to support named return values?

### ISSUE THREAD

**Issue by hkdnet** [moznion/gowrtr#3]
I'd like to generate a function with named return values.

```golang
func Foo()(i int32, err error) {
        return
}
```

Currently, I can generate one as below,

```golang
package main

import (
	"fmt"

	"github.com/moznion/gowrtr/generator"
)

func main() {
	g := generator.NewRoot()

	sig := generator.NewFuncSignature("Foo").AddReturnTypes("i int32", "err error")

	g = g.AddStatements(
		generator.NewFunc(nil, sig, generator.NewReturnStatement()),
	)

	src, _ := g.Generate(0)
	fmt.Print(src)
}
```

However, `AddReturnTypes("i int32", "err error")` seems too hacky. And this hack does not work when the function has only one return type.

```go
// snip
	sig := generator.NewFuncSignature("Foo").AddReturnTypes("err error")
// snip
```

```go
func Foo() err error { // syntax error on this line
        return
}
```

I have two ideas to address this issue. The first is to change `FuncSignature.returnTypes` from `[]string` to `[]*FuncReturnType`. This is straight-forward but it is a bit annoying to write `NewReturnType("", "int32")` every time because names of return values are optional while parameters needs their names.

The second is to allow generators to write function return values with parentheses even though there is only one return value. This is more simple if the unnecessary parentheses acceptable.

Do you have any ideas how to generate functions with named return values? Thanks.

**Comment by moznion** [comment]
That's a good point. I'll consider introducing the `FuncReturnType` to this project.

**Comment by moznion** [comment]
Or here is a bit tricky patch:

```diff
diff --git a/generator/func_signature.go b/generator/func_signature.go
index 54f0205..a7629f0 100644
--- a/generator/func_signature.go
+++ b/generator/func_signature.go
@@ -108,7 +108,14 @@ func (f *FuncSignature) Generate(indentLevel int) (string, error) {
        case 0:
                // NOP
        case 1:
-               stmt += " " + returnTypes[0]
+               retType := returnTypes[0]
+               openingLit := " "
+               closingLit := ""
+               if strings.Contains(retType, " ") {
+                       openingLit = " ("
+                       closingLit = ")"
+               }
+               stmt += openingLit + retType + closingLit
        default:
                stmt += " (" + strings.Join(returnTypes, ", ") + ")"
        }
diff --git a/generator/func_signature_test.go b/generator/func_signature_test.go
index 00969a8..a97b897 100644
--- a/generator/func_signature_test.go
+++ b/generator/func_signature_test.go
@@ -91,3 +91,17 @@ func TestShouldRaiseErrorWhenLastFuncParameterTypeIsEmpty(t *testing.T) {
        _, err := sig.Generate(0)
        assert.EqualError(t, err, errmsg.LastFuncParameterTypeIsEmptyErr().Error())
 }
+
+func TestShouldGeneratingFuncSignatureWithNamedReturnValue(t *testing.T) {
+       {
+               sig, err := NewFuncSignature("myFunc").ReturnTypes("err error").Generate(0)
+               assert.NoError(t, err)
+               assert.Equal(t, "myFunc() (err error)", sig)
+       }
+
+       {
+               sig, err := NewFuncSignature("myFunc").ReturnTypes("s string", "err error").Generate(0)
+               assert.NoError(t, err)
+               assert.Equal(t, "myFunc() (s string, err error)", sig)
+       }
+}
```

How do you feel this, @hkdnet?

**Comment by hkdnet** [comment]
This means,

- `FuncSignature.returnTypes` is still `[]string` and we can call `AddReturnType` with `"TypeName"`, `"name TypeName"`, or `"name"` (which is `a` of `func Foo() (a, b int32)`).
- Generator writes parentheses if needed. That is, when a function has 2 or more return values OR a function has one **named** return value.

Is this right? It looks very good to me :+1:

**Comment by moznion** [comment]
Yes, it is. If there is no problem, I'll apply the above patch and release it. Is it OK?

**Comment by moznion** [comment]
NOTE: The reason for the decision that still using `[]string` as a parameter type is for keeping the backward compatibilities.

**Comment by hkdnet** [comment]
> If there is no problem, I'll apply the above patch and release it. Is it OK?

No problem. Thank you for your quick response 😄

**Comment by moznion** [comment]
08e30cf60446ab679e314f94b08f48ee26c435c2 fixed this issue.
Thank you very much for your suggestion, @hkdnet 🍺
